### ISSUE TITLE
False positive read

### ISSUE THREAD

**Issue by evansharp** [ardavast/nespad#1]
Hello,

What could be the cause of a false-positive read for all buttons all the time? 

When trying the simple example provided, my serial monitor is just spammed by all the outputs in the order they appear. Actually pressing a button has no effect.

I have tried this with an authentic Nintendo NES controller and a modern Chinese knockoff with the same results.

Thanks for any ideas!
Evan

![Screen Recording 2020-11-24 at 10 25 48 PM](https://user-images.githubusercontent.com/1461350/100191368-d8b22580-2ea4-11eb-9ce0-d096666d545d.gif)

**Comment by ardavast** [comment]
Sorry, This is something I uploaded just for backup purposes, I didn't expect that anyone else might try to use it :)
I changed the code a bit since then - I will try to update the repo with the working code tomorrow.

However, the problem that you're describing can certainly happen if some of the connections are left open, for example it will happen if GND is connected but 5V is not - please check if all 5 wires are connected properly.
You can see the pinout at the bottom of this page: https://pinoutguide.com/Game/snescontroller_pinout.shtml
The example assumes that clock, latch and data are connected to pins 2, 3, and 4 on the Arduino and that 5V and GND are also connected to the Arduino.

**Comment by evansharp** [comment]
Thanks! I look forward to seeing the updated code!

**Comment by ardavast** [comment]
Hi, I made a short video using the example from this repository, without making any changes to the code: https://youtu.be/06xAtD3_JN4. I'm using M-M pin headers inserted into the gamepad port, and F-M jumper wires to connect them to the Arduino.  As you can see at the end of the video, I'm able to replicate this behavior by pulling out the 5V wire and when I insert it back everything works properly again. So please double-check check your wiring.

Additionally, you can also try the code from this article: https://www.allaboutcircuits.com/projects/nes-controller-interface-with-an-arduino-uno/

**Comment by evansharp** [comment]
Thanks for all this! You've definitely made me suspicious of my Leonardo's pre-installed headers. Since this application will be permanent, I'm considering soldering the connections right to the back of the board; shame though.

I have seen the other article you linked, as well as several others. I'm pretty certain at this point that the code is not the issue.

I appreciate the support and will have a go at the wiring again.
